### PR TITLE
Updates to v5.1.0, adds @anjos as maintainer

### PR DESCRIPTION
**Pull request by anjos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: #4
Closes: #5
Closes: #6
Closes: #7 
Closes: #8

### CODE REVIEW

**Comment by anjos** [comment]
@conda-forge-admin, please rerender

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by anjos** [comment]
@conda-forge-admin, please ping team

**Comment by anjos** [comment]
@conda-forge/staged-recipes: only reviewer is not replying - could somebody with powers please merge this?  Thanks in advance.

**Review by goanpeca — APPROVED** [review]

**Comment by anjos** [comment]
@goanpeca thanks for reviewing this.  Could you also merge it?

**Comment by goanpeca** [comment]
Do not have the right. @jaimergp could you merge?

**Pull request merged**
